source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MBStaticCollectionView_Example', :exclusive => true do
  pod "MBStaticCollectionView", :path => "../"
end

target 'MBStaticCollectionView_Tests', :exclusive => true do
  pod "MBStaticCollectionView", :path => "../"

  
end
